recipe: default.v1

assistant_id: 20240305-143448-principal-weight

language: vi

pipeline:
  - name: "SpacyNLP"
    model: "vi_core_news_lg"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.7
    core_fallback_action_name: action_default_fallback
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true

ignore_intents:
  - speak_chao_hoi
  - speak_thoi_gian
  - speak_dia_chi
  - speak_chuc_nang
  - speak_cam_on
  - speak_ask_create_account
  - speak_no_account
  - speak_tam_biet
  - speak_iamabot
  - choose_courseid_to_register
  - choose_teacher
